--Library Items ...
--Texture Library Items ...
texturesCount = 3 ;
    texture0_name = "aladdin_aladdin_sheet.png" ;
    texture0_path = "\res\textures\aladdin_aladdin_sheet.png" ;
    texture1_name = "ball.png" ;
    texture1_path = "\res\textures\ball.png" ;
    texture2_name = "gr.png" ;
    texture2_path = "\res\textures\gr.png" ;
--End of Texture Library Items ...
--End of Library Items ...
