--sprite...
name = "sprite_2" ;
image = "player.png" ;
x = 379 ;
y = 259 ;
height = 163 ;
width = 100 ;
rotation = 0 ;
scale = 0.8 ;
alpha = 255 ;
isPhysical = true ;
isStatic = false ;
mass = 100 ;
inertia = 0.1 ;
friction = 0 ;
elastic = 0 ;
--Shapes...
    --LineShapes...
    lineShapesCount = 0 ;
    --End of LineShapes...
    --CircleShapes...
    circleShapesCount = 1 ;
        --circleShape_0...
        circleShape_0_x = 0 ;
        circleShape_0_y = 0 ;
        circleShape_0_r = 89 ;
    --End of CircleShapes...
    -- PolyGonShapes...
    polyGonShapesCount = 0 ;
    --End of PolyGonShapes...
--End of sprite...

--Functions ...

--End of Functions ...