--sprite...
name = "sprite_0" ;
image = "pad_big_L2.png" ;
x = 600 ;
y = 540 ;
height = 121 ;
width = 1215 ;
rotation = 0 ;
scale = 1 ;
alpha = 255 ;
isPhysical = true ;
isStatic = true ;
mass = 0 ;
inertia = 0 ;
friction = 0.5 ;
elastic = 0.5 ;
--Shapes...
    --LineShapes...
    lineShapesCount = 1 ;
        --lineShape_0...
        lineShape_0_aX = -569 ;
        lineShape_0_aY = 1 ;
        lineShape_0_bX = 565 ;
        lineShape_0_bY = 1 ;
        lineShape_0_thickness = 40 ;
    --End of LineShapes...
    --CircleShapes...
    circleShapesCount = 0 ;
    --End of CircleShapes...
    -- PolyGonShapes...
    polyGonShapesCount = 0 ;
    --End of PolyGonShapes...
--End of sprite...

--Functions ...

--End of Functions ...