--sprite...
name = "sprite_6" ;
image = "asteroid.tga" ;
x = 221 ;
y = 144 ;
height = 60 ;
width = 60 ;
rotation = 0 ;
scale = 1 ;
alpha = 255 ;
isPhysical = true ;
isStatic = false ;
mass = 100 ;
inertia = 0.5 ;
friction = 0.5 ;
elastic = 0.5 ;
--Shapes...
    --LineShapes...
    lineShapesCount = 0 ;
    --End of LineShapes...
    --CircleShapes...
    circleShapesCount = 1 ;
        --circleShape_0...
        circleShape_0_x = 0 ;
        circleShape_0_y = 0 ;
        circleShape_0_r = 31 ;
    --End of CircleShapes...
    -- PolyGonShapes...
    polyGonShapesCount = 0 ;
    --End of PolyGonShapes...
--End of sprite...

--Functions ...

--End of Functions ...